# Generated by Django 4.2.2 on 2023-06-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descpition',
            new_name='description',
        ),
    ]
