# Generated by Django 4.2.2 on 2023-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_marks_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
