# Generated by Django 4.2.2 on 2023-07-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_marks_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
