# Generated by Django 4.2.2 on 2023-07-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='togo_events',
            field=models.TextField(blank=True),
        ),
    ]
