# Generated by Django 4.2.2 on 2023-07-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_liked_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='type',
            field=models.CharField(blank=True, default='Не указано', max_length=255),
        ),
    ]
